import Header from "@/components/Header";
import "../styles/global.css";
import { Poppins } from "next/font/google";
import Providers from "@/components/Providers";

const poppins = Poppins({
  weight: ["500", "400", "100", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "NXTHOUSE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
