"use client";

import Header from "@/components/Header";
import "../styles/global.css";
import { Poppins } from "next/font/google";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import React from "react";
import { AnimatePresence } from 'framer-motion'

const poppins = Poppins({
  weight: ["500", "400", "100", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "NXTHOUSE",
  description: "Generated by create next app",
};

interface RootProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="en">
      <AnimatePresence mode="wait"  onExitComplete={() => window.scrollTo(0, 0)}>
      <body className={poppins.className}>
        <Providers>
          <Toaster position="top-center" reverseOrder={false} />

          <Header />
          {children}
        </Providers>

        
      </body>
      </AnimatePresence>
      
    </html>
  );
}
